template_path: lambda.yaml
parameters:
  FunctionName: SiteMonitor
  HandlerName: site_monitor_handler
  Timeout: "60"
  ProjectCode: {{ stack_group_config.project_code }}
  UseCustomIAMPolicy: "true"
  AlarmTopicName: {{ stack_group_config.project_alert_topic }}
dependencies:
  - SiteMonitor/policy.yaml
