template_path: dynamo.yaml
parameters:
  TableName: SiteMonitoring
  PrimaryKeyName: site
  PrimaryKeyType: S
  RangeKeyName: timestamp
  RangeKeyType: S
  ProjectCode: {{ stack_group_config.project_code }}
