AWSTemplateFormatVersion: 2010-09-09
Description: Scheduled CloudWatch Event Rule
Parameters:
  FunctionName:
    Type: String
    Description: Name for Function
  CronExpression:
    Type: String
    Description: Cron Schedule Expression
Resources:
  RuleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FunctionName}
      RoleName: !Sub ${FunctionName}CronRole
  Rule:
    Type: AWS::Events::Rule
    Properties: 
      Description: !Sub Scheduled Event for ${FunctionName} Lambda
      Name: !Sub ${FunctionName}Cron
      ScheduleExpression: !Sub cron(${CronExpression})
      State: ENABLED
      Targets:
        - Arn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FunctionName}
          Id: !Ref FunctionName
    DependsOn:
      - RuleRole
